spring:
  application:
    name: rag

  ai:
    # 阿里百炼
    dashscope:
      api-key: sk-1308c476504a4d7c9c08c4b51bd1937a
      # 设置向量模型
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 2048

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
