spring:
  application:
    name: rag

  ai:
    # 阿里百炼
    dashscope:
      api-key: sk-1308c476504a4d7c9c08c4b51bd1937a
      # 设置大语言模型
      chat:
        options:
          model: qwen-plus
      # 设置向量模型
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
#          username: "root"
#          password: "milvus"
        databaseName: "default"
        collectionName: "test"
        embeddingDimension: 1024
        indexType: IVF_FLAT
        metricType: COSINE

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
