spring:
  application:
    name: quick-start

  # deepseek
  ai:
    deepseek:
      api-key: sk-1308c476504a4d7c9c08c4b51bd1937a
      chat:
        options:
          model: deepseek-chat
  # 阿里百炼
    dashscope:
      api-key: sk-1308c476504a4d7c9c08c4b51bd1937a
      chat:
        options:
          model: